import type { Author, Post } from "./types";

const TEAM: Author = {
  name: "The Jobsynk AI Team",
  role: "Resume, ATS & hiring research",
  initials: "JS",
};

export const NEW_POSTS: Post[] = [
  {
    slug: "federal-resume-two-page-limit-2026",
    title: "Federal Resume Two-Page Limit: The 2026 USAJOBS Rules",
    seoTitle: "Federal Resume Two-Page Limit: 2026 USAJOBS Guide",
    description: "Federal resumes are now capped at two pages. Learn what USAJOBS requires, what to cut, and how to prove specialized experience without being screened out.",
    excerpt: "The old five-page federal resume is gone. Here is how to fit specialized experience, grades, dates, and measurable evidence into the new two-page USAJOBS format.",
    publishedAt: "2026-07-29",
    updatedAt: "2026-07-29",
    author: TEAM,
    tags: ["Federal jobs", "Formatting", "2026 guide"],
    readingMinutes: 7,
    hero: "funnel",
    heroImage: "/blog/federal-resume-two-page-limit-2026.jpg",
    heroAlt: "Two resume pages passing through a formal document checkpoint with an approval mark",
    tone: "accent",
    faq: [
      { q: "Are federal resumes limited to two pages in 2026?", a: "Yes. USAJOBS says federal agencies only accept resumes of two pages or less under the Merit Hiring Plan. Follow the limit and the instructions in each announcement." },
      { q: "What must a federal resume include?", a: "Include contact information and relevant work, education, skills, and accomplishments that prove the announced qualifications. Current and former federal employees should also include pay plan, occupational series, and grade." },
      { q: "Should a federal resume include hours worked per week?", a: "Include hours when the announcement or experience requirement makes them relevant, especially when eligibility depends on full-time-equivalent specialized experience." },
      { q: "What file format should I upload to USAJOBS?", a: "USAJOBS recommends PDF to preserve formatting and page count. The file must be 5 MB or less; Word and several other formats are also accepted." },
    ],
    body: [
      { type: "takeaways", items: [
        "Federal agencies now accept resumes of **two pages or less**. The transition ended on September 27, 2025.",
        "A longer attachment is not a workaround: a lone overlength resume can make the application ineligible.",
        "Match every line to the announcement's **qualifications, specialized experience, and evaluation criteria**.",
        "Keep federal identifiers that establish eligibility; remove generic duties, references, photos, and unrelated history.",
      ] },
      { type: "p", text: "For years, federal applicants were told to write a four-, five-, or even seven-page career record. That advice is obsolete. The [USAJOBS Help Center](https://help.usajobs.gov/faq/application/documents/resume/page-limit) now states the rule plainly: your resume must be two pages or less." },
      { type: "p", text: "This is not an invitation to squeeze an old resume into tiny type. The application has changed from a career archive into a qualification brief. Your two pages must let a reviewer verify, without assumptions, that you meet the announcement." },
      { type: "h2", id: "what-the-rule-requires", text: "What does the federal two-page rule require?" },
      { type: "table", head: ["Requirement", "What to do"], rows: [
        ["Length", "Submit no more than two pages."],
        ["File", "Use a readable file under 5 MB; USAJOBS recommends PDF."],
        ["Federal history", "For federal roles, include pay plan, series, and grade."],
        ["Evidence", "Address the announcement's qualifications with specific work."],
        ["Privacy", "Leave out SSN, age, photos, and sensitive information."],
      ], caption: "Additional required documents do not replace the compliant resume." },
      { type: "callout", tone: "rose", title: "Do not hide a longer resume in another attachment", text: "OPM's [agency guidance](https://www.opm.gov/policy-data-oversight/hiring-information/merit-hiring-plan-resources/agency-guidance-on-the-two-page-limit-on-resume-length.pdf) says that when the only resume received is longer than two pages, the applicant is ineligible for further consideration." },
      { type: "h2", id: "what-to-keep", text: "What deserves space on a two-page federal resume?" },
      { type: "ol", items: [
        "**Exact specialized experience.** Show where and how you performed the work.",
        "**Scope.** Add team size, budget, caseload, systems, geography, or risk level.",
        "**Results.** State what changed: time fell, compliance improved, or a backlog cleared.",
        "**Eligibility details.** Retain federal series, grade, dates, and hours when relevant.",
        "**Required education or credentials.** Include what the announcement uses to qualify applicants.",
      ] },
      { type: "sample", label: "Compressed federal accomplishment", text: "Program Analyst, GS-0343-12 | May 2022–Present\nLed quarterly reporting for a $28M grant portfolio across 14 recipients; rebuilt validation, cutting corrections 31% and delivering every FY2025 report before deadline." },
      { type: "h2", id: "what-to-cut", text: "What should you cut first?" },
      { type: "ul", items: [
        "A generic objective such as *seeking a challenging federal position*.",
        "References and every duty copied from a position description.",
        "Unrelated old roles that establish no qualification.",
        "Soft-skill lists, outdated training, and expired credentials.",
        "Repeated accomplishments across similar positions.",
      ] },
      { type: "h2", id: "tailor-to-announcement", text: "How do you tailor without keyword stuffing?" },
      { type: "p", text: "Read **Qualifications**, **Specialized experience**, **How you will be evaluated**, then **Duties**. Build one evidence line for each required element. Use the agency's term when it truthfully describes your work, then prove it with scope and an outcome." },
      { type: "callout", tone: "mint", title: "Final two-page check", text: "Can a reviewer find every qualification in 10–15 seconds? Is the text selectable? Run the file through our [free ATS checker](/ats-checker), then compare it against the announcement once more." },
    ],
  },
  {
    slug: "resume-summary-examples-2026",
    title: "Resume Summary Examples That Sound Specific, Not Generic",
    seoTitle: "Resume Summary Examples for 2026 (With a Simple Formula)",
    description: "Use this practical resume-summary formula and role-specific examples to write a sharp opening that proves your value without clichés or empty adjectives.",
    excerpt: "A good summary is not a personality paragraph. It is a three-line argument for fit. Use this formula and adapt the examples without copying generic claims.",
    publishedAt: "2026-07-28",
    updatedAt: "2026-07-28",
    author: TEAM,
    tags: ["Resume examples", "Writing", "Career strategy"],
    readingMinutes: 7,
    hero: "signal",
    heroImage: "/blog/resume-summary-examples-2026.jpg",
    heroAlt: "A resume with its professional summary highlighted in lavender and mint",
    tone: "mint",
    faq: [
      { q: "How long should a resume summary be?", a: "Aim for two to four lines, usually 40 to 70 words. Establish your target role, relevant evidence, and differentiator without pushing experience off page one." },
      { q: "Should a resume summary use first person?", a: "Use implied first person: write 'Product manager with seven years...' rather than 'I am...' Avoid third-person pronouns and your own name." },
      { q: "Do fresh graduates need a resume summary?", a: "Only when it adds positioning. Lead with degree, relevant projects, tools, and the problems you can solve; skip an empty objective." },
      { q: "Should I change my summary for every application?", a: "Yes. Match the target title and foreground the capabilities the role values most, without adding anything untrue." },
    ],
    body: [
      { type: "takeaways", items: [
        "Answer three questions: **what role are you**, **what evidence proves it**, and **why are you relevant here**?",
        "Use 40–70 words. Two concrete details beat six adjectives.",
        "Lead with professional identity, not *results-driven professional*.",
        "Tailor the nouns and evidence to the job; never copy the whole posting.",
      ] },
      { type: "p", text: "Many summaries spend the most valuable part of the page saying nothing: *motivated team player with excellent communication skills seeking a challenging opportunity*. Every applicant can claim that sentence, so it helps no applicant." },
      { type: "p", text: "A useful summary behaves like a search-result snippet. It gives the recruiter enough evidence to decide the rest of the page is worth reading." },
      { type: "h2", id: "summary-formula", text: "What is the simplest resume-summary formula?" },
      { type: "sample", label: "The formula", text: "[Target role / professional identity] with [relevant scope or experience]. [One proof point with a number, outcome, or recognizable context]. [Two or three capabilities that match this role]." },
      { type: "h2", id: "examples", text: "What do strong resume summaries look like by role?" },
      { type: "table", head: ["Role", "Example summary"], rows: [
        ["Software engineer", "Backend engineer with five years building payment and identity services. Cut checkout API latency 42% and helped migrate 18 services to event-driven workflows. Strong in Go, PostgreSQL, and observability."],
        ["Product manager", "B2B product manager who led a billing redesign used by 11,000 accounts and reduced support contacts 24%. Best at customer research, prioritization, and cross-functional delivery."],
        ["Data analyst", "Data analyst who automated weekly reporting across 32 locations, saving 14 hours per cycle. Advanced SQL, Power BI, experimentation, and stakeholder communication."],
        ["Marketing manager", "Growth marketer who increased trial-to-paid conversion from 18% to 24% through onboarding and email experiments. Experienced in acquisition, CRM, and retention."],
        ["Customer success", "Customer success manager supporting SaaS portfolios up to $3.2M ARR. Improved renewal rate eight points through risk reviews and role-based onboarding."],
        ["Fresh graduate", "Computer science graduate who deployed three full-stack projects, including a booking tool used by 240 students. Comfortable with React, Python, SQL, and Git."],
      ] },
      { type: "h2", id: "career-change-summary", text: "How should a career changer write the summary?" },
      { type: "p", text: "Do not open with what you lack. Name the destination role, then bridge to it with evidence. A teacher moving into customer success is a client-facing educator who has onboarded, retained, and supported a demanding user group." },
      { type: "sample", label: "Career-change example", text: "Customer enablement specialist transitioning from eight years in education. Designed onboarding used by 600 learners and coached 40 colleagues through a new platform. Brings facilitation, adoption, and high-empathy problem solving to SaaS." },
      { type: "h2", id: "summary-mistakes", text: "Which summary mistakes make a resume weaker?" },
      { type: "ul", items: [
        "**Adjective stacking:** dynamic, passionate, strategic, innovative.",
        "**Biography mode:** explaining the whole career instead of this application.",
        "**Unsupported seniority:** claiming expertise without scope or results.",
        "**Keyword soup:** listing tools with no relationship to performed work.",
        "**An objective in disguise:** describing what you want, not what you contribute.",
      ] },
      { type: "callout", tone: "mint", title: "Write the summary last", text: "Choose the four strongest facts from your experience, then write around those facts and the target job. If evidence is absent from the body, it does not belong in the opening." },
      { type: "callout", tone: "accent", title: "Do this next", text: "Find the [resume keywords that matter](/blog/resume-keywords-that-matter), revise the nouns in your summary, then use the [free ATS checker](/ats-checker) to confirm clean parsing." },
    ],
  },
  {
    slug: "how-long-should-a-resume-be-2026",
    title: "How Long Should a Resume Be in 2026?",
    seoTitle: "How Long Should a Resume Be? One Page vs Two (2026)",
    description: "One page or two? Use this evidence-first decision guide to choose the right resume length for your experience, industry, and target role in 2026.",
    excerpt: "The right resume length is not a status symbol. Use one page when it tells the whole relevant story and two when the second page contains evidence worth reading.",
    publishedAt: "2026-07-27",
    updatedAt: "2026-07-29",
    author: TEAM,
    tags: ["Resume basics", "Formatting", "2026 guide"],
    readingMinutes: 6,
    hero: "layers",
    heroImage: "/blog/how-long-should-a-resume-be-2026.jpg",
    heroAlt: "A one-page resume and a two-page resume balanced on a comparison scale",
    tone: "sky",
    faq: [
      { q: "Is a two-page resume acceptable in 2026?", a: "Yes. Use two pages when both contain recent, relevant evidence. The second page is a problem only when it is filler." },
      { q: "Should a new graduate use a one-page resume?", a: "Usually. One page normally fits education, internships, projects, skills, and leadership. Add a second only for substantial relevant experience." },
      { q: "Is a three-page resume ever acceptable?", a: "Occasionally for academic or medical CVs and applications requesting extensive publications or projects. For a standard private-sector resume, three pages usually signals weak editing." },
      { q: "Can a federal resume be longer than two pages?", a: "Not for current federal applications covered by the Merit Hiring Plan. Follow the announcement and official USAJOBS guidance." },
    ],
    body: [
      { type: "takeaways", items: [
        "Use **one page** when it contains all evidence needed to understand your fit.",
        "Use **two pages** when page two adds relevant achievements, technical depth, projects, or credentials.",
        "Do not force one page with tiny type or crowded margins.",
        "Federal applications are special: current USAJOBS guidance sets a firm **two-page maximum**.",
      ] },
      { type: "p", text: "Resume-length advice is often reduced to one page under ten years and two pages over ten. That shortcut is easy to remember and frequently wrong. Relevance, not elapsed time, decides how much space you need." },
      { type: "p", text: "A product manager with twelve repetitive years may have a sharp one-page resume. A cloud engineer with six years, major migrations, and certifications may need two. Ask not *how long have I worked?* but *how much proof does this application need?*" },
      { type: "h2", id: "one-page", text: "When is a one-page resume better?" },
      { type: "ul", items: [
        "You are a student, graduate, or early-career applicant with few relevant roles.",
        "You are making a focused move and older experience does not support the target.",
        "Your accomplishments, skills, education, and projects fit at readable size.",
        "Concise evidence is an advantage in a fast-moving hiring process.",
      ] },
      { type: "callout", tone: "butter", title: "One page is not automatically more impressive", text: "A dense wall of 9-point text is harder to scan than a clean page and a half. If cutting removes the evidence that proves you can do the job, shorter is worse." },
      { type: "h2", id: "two-pages", text: "When does a second page earn its place?" },
      { type: "table", head: ["Good reason for page two", "Weak reason"], rows: [
        ["Recent roles contain distinct, relevant achievements.", "Every role repeats the same duties."],
        ["Projects prove technical depth.", "A full page lists tools without context."],
        ["Licenses, publications, or credentials matter.", "Expired credentials fill space."],
        ["Leadership scope and technical depth both matter.", "A profile repeats the bullets below."],
      ] },
      { type: "h2", id: "what-to-cut", text: "What should you cut before adding a page?" },
      { type: "ol", items: [
        "Remove generic objective and summary language.",
        "Delete bullets describing baseline duties rather than outcomes.",
        "Combine repeated accomplishments across similar roles.",
        "Reduce positions older than 10–15 years to relevant details.",
        "Remove references, rating bars, and explanations of familiar tools.",
      ] },
      { type: "h2", id: "page-break", text: "Where should a two-page resume break?" },
      { type: "p", text: "Never split a short bullet or strand a heading at the bottom. Break between roles or sections. Put your name and page number on page two, but keep essential contact details in the body of page one so parsers do not miss them." },
      { type: "h2", id: "exceptions", text: "Which resume types follow different rules?" },
      { type: "p", text: "Academic and medical CVs can run many pages. Federal resumes used to be another exception, but the rule changed: read our guide to the [federal two-page resume limit](/blog/federal-resume-two-page-limit-2026) before applying through USAJOBS." },
      { type: "callout", tone: "mint", title: "The final test", text: "At 100% zoom, is every line relevant and readable? Does page two start with meaningful evidence? Then run the PDF through the [free ATS checker](/ats-checker) to confirm the content extracts in order." },
    ],
  },
];
